### ISSUE TITLE
Indicator stick together

### ISSUE THREAD

**Issue by xxzj990** [phuchuynhStrong/worm_indicator#1]
my device screen pixel is 1280x720.

![20190810144123](https://user-images.githubusercontent.com/5134154/62818679-01fa5580-bb7d-11e9-9366-d55fe1bb90d0.jpg)

**Comment by phuchuynhStrong** [comment]
Hi @xxzj990 . Thanks for reporting this. Can you provide more information how to reproduce this ?

**Comment by xxzj990** [comment]
This problem occurs when you slide to the last page，When you are sliding very slowly. @phuchuynhStrong

**Comment by phuchuynhStrong** [comment]
@xxzj990 Sorry for the late reply on this issue. I make some changes in the new version (0.2.1) to fix this. This isn't actually my problem. It's originally Flutter issue which have been fixed in stable channel last month (v1.7.8+hotfix.4). [Here is the fixed issue](https://github.com/flutter/flutter/issues/24763). Please let me know if you see the problem is gone

**Comment by xxzj990** [comment]
@phuchuynhStrong  Thank you for your reply.
My flutter version is Channel stable, v1.7.8+hotfix.4.
And I update 'worm_indicator' to version 0.2.1,this problem still exists.

**Comment by phuchuynhStrong** [comment]
Hi @xxzj990 . I finally found that using `viewportFraction` with `PageController` will cause that problem. The fix is delivered with `0.2.4` version

**Comment by xxzj990** [comment]
@phuchuynhStrong 

0.2.4 work fine.

But need add "physics: AlwaysScrollableScrollPhysics()," to PageView.

Thanks
